[package]
name = "rs-prereq"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.10.3"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
curve25519-dalek = "3.2.1" 
bs58 = "0.5.1"
solana-program = "1.15.0"
solana-sdk = "1.15.0"
solana-client = "1.15.0"

